name: servant-oncall
version:             0.1.0.0
description:
license:             BSD3
#license-file:        LICENSE
author:              Thomas Boeglin / Tharindu Galappaththi
maintainer:          thomas.boeglin@gmail.com
copyright:           2018 Thomas Boeglin / Tharindu Galappaththi
category:            Web
extra-source-files:  README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints



library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Models
    - Queries
  dependencies:
    - base >= 4.7 && < 5
    - aeson
    - ekg
    - mtl
    - servant-server
    - sqlite-simple
    - time
    - wai
    - warp

executables:
  servant-oncall-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - "\"-with-rtsopts=-T -N\"" # https://github.com/sol/hpack/issues/237
    dependencies:
      - base
      - bytestring
      - ekg
      - servant-oncall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
